//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitToGOST.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RevitToGOST.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Empty {
            get {
                object obj = ResourceManager.GetObject("Empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GOST_2_104_2006_Dop_1 {
            get {
                object obj = ResourceManager.GetObject("GOST_2_104_2006_Dop_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GOST_2_104_2006_Dop_2 {
            get {
                object obj = ResourceManager.GetObject("GOST_2_104_2006_Dop_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GOST_2_104_2006_Dop_2a {
            get {
                object obj = ResourceManager.GetObject("GOST_2_104_2006_Dop_2a", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GOST_2_104_2006_Stamp_1 {
            get {
                object obj = ResourceManager.GetObject("GOST_2_104_2006_Stamp_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GOST_2_104_2006_Stamp_2 {
            get {
                object obj = ResourceManager.GetObject("GOST_2_104_2006_Stamp_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GOST_2_104_2006_Stamp_2a {
            get {
                object obj = ResourceManager.GetObject("GOST_2_104_2006_Stamp_2a", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GOST_21_110_2013_Table_1 {
            get {
                object obj = ResourceManager.GetObject("GOST_21_110_2013_Table_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GOST_21_301_2014_Title_2 {
            get {
                object obj = ResourceManager.GetObject("GOST_21_301_2014_Title_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GOST_P_2_106_2019_Table_1 {
            get {
                object obj = ResourceManager.GetObject("GOST_P_2_106_2019_Table_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GOST_P_2_106_2019_Table_5 {
            get {
                object obj = ResourceManager.GetObject("GOST_P_2_106_2019_Table_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GOST_P_21_101_2020_Dop_3 {
            get {
                object obj = ResourceManager.GetObject("GOST_P_21_101_2020_Dop_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GOST_P_21_101_2020_Dop_4 {
            get {
                object obj = ResourceManager.GetObject("GOST_P_21_101_2020_Dop_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GOST_P_21_101_2020_Dop_5 {
            get {
                object obj = ResourceManager.GetObject("GOST_P_21_101_2020_Dop_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GOST_P_21_101_2020_Dop_6 {
            get {
                object obj = ResourceManager.GetObject("GOST_P_21_101_2020_Dop_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GOST_P_21_101_2020_Stamp_3 {
            get {
                object obj = ResourceManager.GetObject("GOST_P_21_101_2020_Stamp_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GOST_P_21_101_2020_Stamp_4 {
            get {
                object obj = ResourceManager.GetObject("GOST_P_21_101_2020_Stamp_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GOST_P_21_101_2020_Stamp_5 {
            get {
                object obj = ResourceManager.GetObject("GOST_P_21_101_2020_Stamp_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GOST_P_21_101_2020_Stamp_6 {
            get {
                object obj = ResourceManager.GetObject("GOST_P_21_101_2020_Stamp_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GOST_P_21_101_2020_Table_7 {
            get {
                object obj = ResourceManager.GetObject("GOST_P_21_101_2020_Table_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GOST_P_21_101_2020_Table_8 {
            get {
                object obj = ResourceManager.GetObject("GOST_P_21_101_2020_Table_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GOST_P_21_101_2020_Title_12 {
            get {
                object obj = ResourceManager.GetObject("GOST_P_21_101_2020_Title_12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GOST_P_21_101_2020_Title_12a {
            get {
                object obj = ResourceManager.GetObject("GOST_P_21_101_2020_Title_12a", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap loading_screen_image {
            get {
                object obj = ResourceManager.GetObject("loading_screen_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_2_104_2006_Dop_1_A3_L {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_2_104_2006_Dop_1_A3_L", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_2_104_2006_Dop_1_A4_P {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_2_104_2006_Dop_1_A4_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_2_104_2006_Dop_2_A3_L {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_2_104_2006_Dop_2_A3_L", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_2_104_2006_Dop_2_A4_P {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_2_104_2006_Dop_2_A4_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_2_104_2006_Dop_2a_A3_L {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_2_104_2006_Dop_2a_A3_L", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_2_104_2006_Dop_2a_A4_P {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_2_104_2006_Dop_2a_A4_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_2_104_2006_Stamp_1_A3_L {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_2_104_2006_Stamp_1_A3_L", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_2_104_2006_Stamp_1_A4_P {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_2_104_2006_Stamp_1_A4_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_2_104_2006_Stamp_2_A3_L {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_2_104_2006_Stamp_2_A3_L", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_2_104_2006_Stamp_2_A4_P {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_2_104_2006_Stamp_2_A4_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_2_104_2006_Stamp_2a_A3_L {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_2_104_2006_Stamp_2a_A3_L", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_2_104_2006_Stamp_2a_A4_P {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_2_104_2006_Stamp_2a_A4_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_21_110_2013_Table_1 {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_21_110_2013_Table_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_21_301_2014_Title_2 {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_21_301_2014_Title_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_P_2_106_2019_Table_1 {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_P_2_106_2019_Table_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_P_2_106_2019_Table_5 {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_P_2_106_2019_Table_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_P_21_101_2020_Dop_3_A3_L {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_P_21_101_2020_Dop_3_A3_L", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_P_21_101_2020_Dop_3_A4_P {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_P_21_101_2020_Dop_3_A4_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_P_21_101_2020_Dop_4_A3_L {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_P_21_101_2020_Dop_4_A3_L", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_P_21_101_2020_Dop_4_A4_P {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_P_21_101_2020_Dop_4_A4_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_P_21_101_2020_Dop_5_A3_L {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_P_21_101_2020_Dop_5_A3_L", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_P_21_101_2020_Dop_5_A4_P {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_P_21_101_2020_Dop_5_A4_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_P_21_101_2020_Dop_6_A3_L {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_P_21_101_2020_Dop_6_A3_L", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_P_21_101_2020_Dop_6_A4_P {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_P_21_101_2020_Dop_6_A4_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_P_21_101_2020_Stamp_3_A3_L {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_P_21_101_2020_Stamp_3_A3_L", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_P_21_101_2020_Stamp_3_A4_P {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_P_21_101_2020_Stamp_3_A4_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_P_21_101_2020_Stamp_4_A3_L {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_P_21_101_2020_Stamp_4_A3_L", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_P_21_101_2020_Stamp_4_A4_P {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_P_21_101_2020_Stamp_4_A4_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_P_21_101_2020_Stamp_5_A3_L {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_P_21_101_2020_Stamp_5_A3_L", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_P_21_101_2020_Stamp_5_A4_P {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_P_21_101_2020_Stamp_5_A4_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_P_21_101_2020_Stamp_6_A3_L {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_P_21_101_2020_Stamp_6_A3_L", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_P_21_101_2020_Stamp_6_A4_P {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_P_21_101_2020_Stamp_6_A4_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_P_21_101_2020_Table_7 {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_P_21_101_2020_Table_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_P_21_101_2020_Table_8 {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_P_21_101_2020_Table_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_P_21_101_2020_Title_12 {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_P_21_101_2020_Title_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_GOST_P_21_101_2020_Title_12a {
            get {
                object obj = ResourceManager.GetObject("Preview_GOST_P_21_101_2020_Title_12a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
